language: python

env:
  - USE_NUMBA=ON PYTHON_VERSION=3.6
  - USE_NUMBA=ON PYTHON_VERSION=3.8
  - USE_NUMBA=OFF PYTHON_VERSION=3.6

before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=${PYTHON_VERSION}
    - source activate testenv
    - |
      if [[ "${PYTHON_VERSION}" == "3.6" ]]; then
        conda install --yes --quiet numpy=1.13.3 matplotlib scipy=1.0 scikit-learn=0.19.1 pandas=0.25.3;
        pip install mne=0.18.2 PyWavelets coverage coveralls tqdm download;
      fi;
    - |
      if [[ "${PYTHON_VERSION}" == "3.8" ]]; then
        pip install -r requirements.txt;
      fi;
    - |
      if [[ ( "${USE_NUMBA}" == "ON" ) && ( "${PYTHON_VERSION}" == "3.6" ) ]]; then
        pip install numba=0.45.1
      fi;
    - pip install pytest coverage flake8 check-manifest pytest-sugar
script:
    - make
    - flake8 --count mne_features
after_success:
  - |
    if [[ "${USE_NUMBA}" == "OFF" ]]; then
      bash <(curl -s https://codecov.io/bash)
    fi
